# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180204_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='female',
            new_name='female_votes',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='male',
            new_name='male_votes',
        ),
    ]
