# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='question',
        ),
        migrations.DeleteModel(
            name='constituency',
        ),
    ]
