# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180204_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='gender_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
