# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_gender_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='female_votes',
            new_name='for_votes',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='male_votes',
            new_name='gender_votes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
