# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='constituency_text',
            field=models.CharField(choices=[('Carlow-Kilkenny', 'Carlow-Kilkenny'), ('Cavan-Monaghan', 'Cavan-Monaghan'), ('Clare', 'Clare'), ('Cork East', 'Cork East'), ('Cork North-Central', 'Cork North-Central'), ('Cork North-West', 'Cork North-West'), ('Cork South-Central', 'Cork South-Central'), ('Cork South-West', 'Cork South-West'), ('Donegal', 'Donegal'), ('Dublin Bay North', 'Dublin Bay North'), ('Dublin Bay South', 'Dublin Bay South'), ('Dublin Central', 'Dublin Central'), ('Dublin Fingal', 'Dublin Fingal'), ('Dublin Mid-West', 'Dublin Mid-West'), ('Dublin North-West', 'Dublin North-West'), ('Dublin Rathdown', 'Dublin Rathdown'), ('Dublin South-Central', 'Dublin South-Central'), ('Dublin South-West', 'Dublin South-West'), ('Dublin West', 'Dublin West'), ('Dun Laoghaire', 'Dun Laoghaire'), ('Galway East', 'Galway East'), ('Galway West', 'Galway West'), ('Kerry', 'Kerry'), ('Kildare North', 'Kildare North'), ('Kildare South', 'Kildare South'), ('Loais', 'Loais'), ('Limerick', 'Limerick'), ('Limerick City', 'Limerick City'), ('Longford-Westmeath', 'Longford-Westmeath'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath East', 'Meath East'), ('Meath West', 'Meath West'), ('Offaly', 'Offaly'), ('Roscommon-Galway', 'Roscommon-Galway'), ('Sligo-Leitrim', 'Sligo-Leitrim'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Carlow-Kilkenny', max_length=250),
        ),
    ]
