# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180204_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='for_votes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='gender_votes',
        ),
    ]
