# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='gender_text',
        ),
    ]
