# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='Age_text',
            new_name='age_text',
        ),
    ]
