# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_constituency_constituency_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='constituency_text',
            field=models.CharField(max_length=250),
        ),
    ]
