# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180225_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
    ]
