# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_choice_con_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='con_id',
            new_name='con',
        ),
    ]
