# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180411_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='con',
        ),
    ]
